# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20160816_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='static/movies/'),
        ),
    ]
